/// <reference path="../pb_data/types.d.ts" />
onRecordUpdate((e) => {
  const original = e.record.original();
  const oldValue = original.get("pdfFileName");
  const newValue = e.record.get("pdfFileName");
  const timestamp = new Date().toISOString();
  const recordId = e.record.id;
  
  // If pdfFileName hasn't changed, allow the update
  if (oldValue === newValue) {
    console.log(`[${timestamp}] pdfFileName audit: Record ${recordId} - NO CHANGE (value: "${oldValue}")`);
    e.next();
    return;
  }
  
  // pdfFileName is being modified - validate the new value
  console.log(`[${timestamp}] pdfFileName audit: Record ${recordId} - MODIFICATION ATTEMPT`);
  console.log(`  Old value: "${oldValue}"`);
  console.log(`  New value: "${newValue}"`);
  
  // Check for auto-generated patterns
  const autoGeneratedPatterns = [
    /\d{2}\d{2}\d{4}/,           // MMDDYYYY pattern
    /\d{8}/,                      // 8-digit date pattern
    /^[a-z0-9]{15,}$/i,          // PocketBase-style auto-generated ID
    /^tmp_/i,                     // Temporary file prefix
    /^auto_/i,                    // Auto-generated prefix
    /^file_\d+$/i,                // Generic file_123 pattern
    /\.[a-z0-9]{32}\.pdf$/i       // Hash-like pattern before .pdf
  ];
  
  const isAutoGenerated = autoGeneratedPatterns.some(pattern => pattern.test(newValue));
  
  // Check if it's a valid complete filename
  const hasToolName = e.record.get("toolName") && newValue.toLowerCase().includes(e.record.get("toolName").toLowerCase());
  const hasDateComponent = /\d{4}[-_]\d{2}[-_]\d{2}|\d{2}[-_]\d{2}[-_]\d{4}|january|february|march|april|may|june|july|august|september|october|november|december|jan|feb|mar|apr|jun|jul|aug|sep|oct|nov|dec/i.test(newValue);
  const hasPdfExtension = newValue.toLowerCase().endsWith('.pdf');
  const isValidComplete = hasPdfExtension && (hasToolName || hasDateComponent);
  
  // Reject if auto-generated pattern detected
  if (isAutoGenerated) {
    console.log(`  REJECTED: Auto-generated pattern detected`);
    console.log(`  Reason: Contains auto-generated markers (date patterns, IDs, or temporary prefixes)`);
    throw new BadRequestError(`pdfFileName cannot be auto-generated or overwritten. Current value: ${oldValue}. To change it, provide a complete, properly formatted filename.`);
  }
  
  // Allow if it's a valid complete filename
  if (isValidComplete) {
    console.log(`  ALLOWED: Valid complete filename`);
    console.log(`  Reason: Contains .pdf extension and (tool name or date component)`);
    e.next();
    return;
  }
  
  // If new value is empty/null, allow it (user clearing the field)
  if (!newValue || newValue.trim() === '') {
    console.log(`  ALLOWED: Field cleared`);
    console.log(`  Reason: New value is empty`);
    e.next();
    return;
  }
  
  // If we reach here, it's an incomplete/malformed filename
  console.log(`  REJECTED: Incomplete or malformed filename`);
  console.log(`  Reason: Missing required components (tool name, date, or .pdf extension)`);
  throw new BadRequestError(`pdfFileName cannot be auto-generated or overwritten. Current value: ${oldValue}. To change it, provide a complete, properly formatted filename.`);
}, "articles");